formatter: markdown

content: |-
  {{ .Providers }}
  {{ .Inputs }}
  {{ .Modules }}
  {{ .Resources }}
  ## Usage
   ```hcl
  {{ include "../../examples/firewall_policy.tf" }}
   ```
  {{ .Outputs }}